### ISSUE TITLE
Issue: a pagina sobre.html está sem conteúdo.

### ISSUE THREAD

**Issue by gustavopereiraliceusantista** [gustavopereiraliceusantista/operacao-software-aplicativos#2]
## O que precisa ser feito

No arquivo sobre.html, onde se vê 

```
  <p>Adicionar conteudo aqui</p>
```

1 - Adicionar qualquer conteúdo html com ao menos 200 carateres
2 - Esta adição deve ser feita somente via Fork
3 - A issue precisa ser referenciada no commit message E na mensagem do Pull Request
4 - Seja objetivo e não engraçadinho

Valor da atividade: 2,0 pontos

**Comment by LuanGCMenezes** [comment]
Eu
